base_global_planner: navfn/NavfnROS 
#base_global_planner: carrot_planner/CarrotPlanner

#base_local_planner: base_local_planner/TrajectoryPlannerROS
base_local_planner: dwa_local_planner/DWAPlannerROS

#TODO tune parameters
TrajectoryPlannerROS:
  max_vel_x: 1
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

DWAPlannerROS:
  holonomic_robot: false
  sim_time: 1.0 # (double, default: 1.0) The amount of time to forward-simulate trajectories in seconds
  min_vel_x: 0.0
  min_trans_vel: 0.0
  min_vel_y: 0.0
  max_vel_y: 0.0 #default:0.35
